### ISSUE TITLE
decode_float is not as flexible as decode (and has an incorrect documentation)

### ISSUE THREAD

**Issue by MOZGIII** [Lakelezz/audiopus#2]
The `Decoder::decode_float` doesn't accept `Option` for input as `decode` does.

**Comment by Lakelezz** [comment]
Thank you!

`Decoder::decode_float` will expect `input` to be  `Option<TP>` now, see commit a95de40e1ae033ca2d37becfa11410d43a654e66.

**Comment by MOZGIII** [comment]
Nice! Should I expect a release soon?

**Comment by Lakelezz** [comment]
Two versions have been released now, v0.1.3 featuring issue #3 and v0.2.0 featuring issue #3 and this breaking one.
