### ISSUE TITLE
Relax `bindgen` version requirement

### ISSUE THREAD

**Issue by MOZGIII** [Lakelezz/audiopus#4]
I'm having an odd issue with linking on a mac and it seems the fix for now would be to relax the `bindgen` dependency requirement to `"*"`.
The core problem issue (and proposed solution) in here: https://github.com/KyleMayes/clang-sys/issues/95
The very core issue is, seems like, with rust linkage system itself, cause it should be ok to link different versions of `clang-sys` to the same `clang` native lib.

**Comment by MOZGIII** [comment]
Sorry, this is a duplicate of https://github.com/Lakelezz/audiopus_sys/issues/2 (which was also filed by me, but I'm lost in the issue trackers).

**Comment by Lakelezz** [comment]
As the referenced issue has been resolved, I will continue to close this issue.
