### ISSUE TITLE
Linking errors on MSVC

### ISSUE THREAD

**Issue by fwcd** [Lakelezz/audiopus#6]
Occassionally, I get the following linker error while building building my project (which depends on this crate) with MSVC:

<details>
<pre>
error: linking with `link.exe` failed: exit code: 1318                                                
  |
...
  = note: libaudiopus_sys-7f4ef8681b454d7c.rlib(opus_decoder.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(opus_decoder.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(repacketizer.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(repacketizer.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(opus_encoder.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(opus_encoder.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(celt_decoder.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(celt_decoder.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(entdec.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(entdec.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(opus.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(opus.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(x86cpu.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(x86cpu.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(dec_API.obj) : warning LNK4099: PDB 'libopus.pdb' was 
not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(dec_API.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(celt_encoder.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(celt_encoder.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(entenc.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(entenc.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(enc_API.obj) : warning LNK4099: PDB 'libopus.pdb' was 
not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(enc_API.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(pitch_sse.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(pitch_sse.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(analysis.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(analysis.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(lin2log.obj) : warning LNK4099: PDB 'libopus.pdb' was 
not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(lin2log.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(log2lin.obj) : warning LNK4099: PDB 'libopus.pdb' was 
not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(log2lin.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(mdct.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(mdct.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(modes.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(modes.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(entcode.obj) : warning LNK4099: PDB 'libopus.pdb' was 
not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(entcode.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(celt.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(celt.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(pitch.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(pitch.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(rate.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(rate.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(bands.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(bands.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(quant_bands.obj) : warning LNK4099: PDB 'libopus.pdb' 
was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(quant_bands.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(celt_lpc.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(celt_lpc.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(vq.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(vq.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_MS_to_LR.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_MS_to_LR.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_decode_pred.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_decode_pred.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(init_decoder.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(init_decoder.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(decoder_set_fs.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(decoder_set_fs.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_frame.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_frame.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_indices.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_indices.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_pulses.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_pulses.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_other.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_other.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_LR_to_MS.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_LR_to_MS.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_encode_pred.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_encode_pred.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(check_control_input.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(check_control_input.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(control_SNR.obj) : warning LNK4099: PDB 'libopus.pdb' 
was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(control_SNR.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(encode_pulses.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(encode_pulses.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(encode_indices.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(encode_indices.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(HP_variable_cutoff.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(HP_variable_cutoff.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(encode_frame_FLP.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(encode_frame_FLP.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(init_encoder.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(init_encoder.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(control_codec.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(control_codec.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(kiss_fft.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(kiss_fft.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(mlp.obj) : warning LNK4099: PDB 'libopus.pdb' was not 
found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(mlp.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(mlp_data.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(mlp_data.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(mathops.obj) : warning LNK4099: PDB 'libopus.pdb' was 
not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(mathops.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(laplace.obj) : warning LNK4099: PDB 'libopus.pdb' was 
not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(laplace.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(cwrs.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(cwrs.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(vq_sse2.obj) : warning LNK4099: PDB 'libopus.pdb' was 
not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(vq_sse2.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_private_IIR_FIR.obj) : warning LNK4099: PDB 
'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_private_IIR_FIR.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info        
          libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_private_down_FIR.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_private_down_FIR.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info      
          libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_private_up2_HQ.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_private_up2_HQ.obj)' 
or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_rom.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_rom.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(PLC.obj) : warning LNK4099: PDB 'libopus.pdb' was not 
found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(PLC.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(CNG.obj) : warning LNK4099: PDB 'libopus.pdb' was not 
found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(CNG.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_pitch_lag.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_pitch_lag.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_NLSF_CB_WB.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_NLSF_CB_WB.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_NLSF_CB_NB_MB.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_NLSF_CB_NB_MB.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_parameters.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_parameters.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_core.obj) : warning LNK4099: PDB 'libopus.pdb' 
was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_core.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(NLSF_unpack.obj) : warning LNK4099: PDB 'libopus.pdb' 
was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(NLSF_unpack.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_gain.obj) : warning LNK4099: PDB 'libopus.pdb' 
was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_gain.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_LTP.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_LTP.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(code_signs.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(code_signs.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(shell_coder.obj) : warning LNK4099: PDB 'libopus.pdb' 
was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(shell_coder.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_pulses_per_block.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(tables_pulses_per_block.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_find_predictor.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_find_predictor.obj)' or at 
'.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_quant_pred.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(stereo_quant_pred.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(gain_quant.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(gain_quant.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(LP_variable_cutoff.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(LP_variable_cutoff.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(noise_shape_analysis_FLP.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(noise_shape_analysis_FLP.obj)' 
or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(find_pitch_lags_FLP.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(find_pitch_lags_FLP.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(find_pred_coefs_FLP.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(find_pred_coefs_FLP.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(process_gains_FLP.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(process_gains_FLP.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(wrappers_FLP.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(wrappers_FLP.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(x86_silk_map.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(x86_silk_map.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(VAD.obj) : warning LNK4099: PDB 'libopus.pdb' was not 
found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(VAD.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(control_audio_bandwidth.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(control_audio_bandwidth.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_private_AR2.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(resampler_private_AR2.obj)' or at 
'.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(LPC_analysis_filter.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(LPC_analysis_filter.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(bwexpander.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(bwexpander.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(LPC_inv_pred_gain.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(LPC_inv_pred_gain.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(sum_sqr_shift.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(sum_sqr_shift.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(NLSF2A.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(NLSF2A.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_pitch.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(decode_pitch.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(NLSF_decode.obj) : warning LNK4099: PDB 'libopus.pdb' 
was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(NLSF_decode.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(inner_prod_aligned.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(inner_prod_aligned.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(biquad_alt.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(biquad_alt.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(bwexpander_FLP.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(bwexpander_FLP.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(schur_FLP.obj) : warning LNK4099: PDB 'libopus.pdb' was not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(schur_FLP.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(k2a_FLP.obj) : warning LNK4099: PDB 'libopus.pdb' was 
not found with 'libaudiopus_sys-7f4ef8681b454d7c.rlib(k2a_FLP.obj)' or at '.\target\debug\deps\libopus.pdb'; linking object as if no debug info
          libaudiopus_sys-7f4ef8681b454d7c.rlib(autocorrelation_FLP.obj) : fatal error LNK1318: Unexpected PDB error; OK (0) **'.\target\debug\deps\libopus.pdb**
</pre>
</details>

Any ideas on this?

**Comment by Lakelezz** [comment]
Hello, this should be resolved with `0.3.0-rc.0`!
